name: Check for new versions
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 9 * * 1,5'

permissions:
  contents: write
  pull-requests: write
jobs:
  add-new-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Run add-new-versions.sh
        id: run
        run: |
          bash scripts/add-new-versions.sh > add-new-versions.output
          if grep -q ^Added add-new-versions.output; then
            new_versions=$(grep ^Added add-new-versions.output)
            echo "new_versions=${new_versions}" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for repository changes
        run: |
          if git diff --name-only --exit-code; then
            echo "No changes found in repository"
            echo "changes_exist=false" >> $GITHUB_ENV
          else
            echo "Changes found in repository"
            git diff --name-only
            echo "changes_exist=true" >> $GITHUB_ENV
          fi
      - name: Create branch, commit and push
        if: ${{ env.changes_exist == 'true' }}
        id: branch
        run: |
          BRANCH="githubaction-add-new-versions-$(date +%Y-%m-%d-%H-%M-%S)"
          echo "SOURCE_BRANCH=${BRANCH}" >> "$GITHUB_ENV"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b "$BRANCH"
          git commit -a -m "Adding new versions"
          git push origin "$BRANCH"
      - name: Prepare PR text
        env:
          NEW_VERSIONS: ${{ steps.run.outputs.new_versions }}
        run: |
          {
            echo 'PR_BODY<<EOF'
            echo -e "${NEW_VERSIONS}\\n\\nAuto-generated by GitHub Actions, initiated by @${GITHUB_ACTOR}\\n\\n"
            echo -e "## Validation Steps\\n\\n- The PR must pass all status checks,\\n- Must be reviewed by at least 1 \`CODEOWNER\`, and"
            echo -e "- For the checks to run, the PR must have a review submitted first."
            echo -e "\\n\\n After status checks pass the PR can be merged. Once merged (or closed) the branch will be auto cleaned up."
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Create Pull Request
        if: ${{ env.changes_exist == 'true' }}
        id: cpr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: "Adding new versions"
        run: |
          EXISTING_PR=$(gh pr list --limit 500 --json title,url | jq --arg title "${PR_TITLE}" -r '.[] | select(.title==$title) | .url')
          CREATED_PR=$(gh pr create --title "${PR_TITLE}" --body "${PR_BODY}" --label "status/auto-created" --base "${GITHUB_REF_NAME}" --head "${SOURCE_BRANCH}")
          echo "Created pull request: ${CREATED_PR}" >> $GITHUB_STEP_SUMMARY
          if [ -n "${EXISTING_PR}" ]; then
              gh pr close --comment "Superseded by ${CREATED_PR}" --delete-branch "${EXISTING_PR}"
              echo "Closed previous pull request: ${EXISTING_PR}" >> $GITHUB_STEP_SUMMARY
          fi
